// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for DeviceNotificationStatus.
const (
	Disabled DeviceNotificationStatus = "disabled"
	Enabled  DeviceNotificationStatus = "enabled"
	Unknown  DeviceNotificationStatus = "unknown"
)

// Valid indicates whether the value is a known member of the DeviceNotificationStatus enum.
func (e DeviceNotificationStatus) Valid() bool {
	switch e {
	case Disabled:
		return true
	case Enabled:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for DevicePlatform.
const (
	Ios DevicePlatform = "ios"
)

// Valid indicates whether the value is a known member of the DevicePlatform enum.
func (e DevicePlatform) Valid() bool {
	switch e {
	case Ios:
		return true
	default:
		return false
	}
}

// Defines values for MessageInputFormat.
const (
	Monospace MessageInputFormat = "monospace"
	Plain     MessageInputFormat = "plain"
)

// Valid indicates whether the value is a known member of the MessageInputFormat enum.
func (e MessageInputFormat) Valid() bool {
	switch e {
	case Monospace:
		return true
	case Plain:
		return true
	default:
		return false
	}
}

// Defines values for MessageInputSound.
const (
	Default MessageInputSound = "default"
	None    MessageInputSound = "none"
)

// Valid indicates whether the value is a known member of the MessageInputSound enum.
func (e MessageInputSound) Valid() bool {
	switch e {
	case Default:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for PairingStatus.
const (
	PairingStatusApproved PairingStatus = "approved"
	PairingStatusDenied   PairingStatus = "denied"
	PairingStatusExpired  PairingStatus = "expired"
	PairingStatusPending  PairingStatus = "pending"
)

// Valid indicates whether the value is a known member of the PairingStatus enum.
func (e PairingStatus) Valid() bool {
	switch e {
	case PairingStatusApproved:
		return true
	case PairingStatusDenied:
		return true
	case PairingStatusExpired:
		return true
	case PairingStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for PairingCreatedStatus.
const (
	PairingCreatedStatusPending PairingCreatedStatus = "pending"
)

// Valid indicates whether the value is a known member of the PairingCreatedStatus enum.
func (e PairingCreatedStatus) Valid() bool {
	switch e {
	case PairingCreatedStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for SenderCredentialKind.
const (
	Automation SenderCredentialKind = "automation"
	PairedCli  SenderCredentialKind = "paired_cli"
)

// Valid indicates whether the value is a known member of the SenderCredentialKind enum.
func (e SenderCredentialKind) Valid() bool {
	switch e {
	case Automation:
		return true
	case PairedCli:
		return true
	default:
		return false
	}
}

// Defines values for CreatePairingJSONBodyPlatform.
const (
	Darwin  CreatePairingJSONBodyPlatform = "darwin"
	Linux   CreatePairingJSONBodyPlatform = "linux"
	Windows CreatePairingJSONBodyPlatform = "windows"
)

// Valid indicates whether the value is a known member of the CreatePairingJSONBodyPlatform enum.
func (e CreatePairingJSONBodyPlatform) Valid() bool {
	switch e {
	case Darwin:
		return true
	case Linux:
		return true
	case Windows:
		return true
	default:
		return false
	}
}

// Device defines model for Device.
type Device struct {
	Eligible           bool                     `json:"eligible"`
	Id                 DeviceId                 `json:"id"`
	Name               string                   `json:"name"`
	NotificationStatus DeviceNotificationStatus `json:"notificationStatus"`
	Platform           DevicePlatform           `json:"platform"`
}

// DeviceNotificationStatus defines model for Device.NotificationStatus.
type DeviceNotificationStatus string

// DevicePlatform defines model for Device.Platform.
type DevicePlatform string

// DeviceId defines model for DeviceId.
type DeviceId = string

// Error defines model for Error.
type Error struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestId string `json:"requestId"`

	// RetryAfter Seconds until a retry is permitted.
	RetryAfter *int `json:"retryAfter,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// IssuedCredential Returned once after pairing approval or token creation.
type IssuedCredential struct {
	Name  string `json:"name"`
	Token string `json:"token"`
}

// MessageAccepted defines model for MessageAccepted.
type MessageAccepted struct {
	AcceptedAt       time.Time `json:"acceptedAt"`
	Id               MessageId `json:"id"`
	LogicalMessageId string    `json:"logicalMessageId"`
	TargetCount      int       `json:"targetCount"`
}

// MessageId defines model for MessageId.
type MessageId = string

// MessageInput defines model for MessageInput.
type MessageInput struct {
	Body string `json:"body"`

	// Devices Receiving-device nicknames. Omit to target all eligible devices.
	Devices  *[]string             `json:"devices,omitempty"`
	Format   *MessageInputFormat   `json:"format,omitempty"`
	Group    *RestrictedIdentifier `json:"group,omitempty"`
	Image    *string               `json:"image,omitempty"`
	Key      *RestrictedIdentifier `json:"key,omitempty"`
	Sound    *MessageInputSound    `json:"sound,omitempty"`
	Subtitle *string               `json:"subtitle,omitempty"`
	Title    *string               `json:"title,omitempty"`
	Url      *string               `json:"url,omitempty"`
}

// MessageInputFormat defines model for MessageInput.Format.
type MessageInputFormat string

// MessageInputSound defines model for MessageInput.Sound.
type MessageInputSound string

// MessagePage defines model for MessagePage.
type MessagePage struct {
	Items      []MessageSummary `json:"items"`
	NextCursor *string          `json:"nextCursor,omitempty"`
}

// MessageSummary defines model for MessageSummary.
type MessageSummary struct {
	AcceptedAt time.Time `json:"acceptedAt"`
	Body       string    `json:"body"`
	Id         MessageId `json:"id"`
	Read       bool      `json:"read"`
	SenderName string    `json:"senderName"`
	Subtitle   *string   `json:"subtitle,omitempty"`
	Title      string    `json:"title"`
}

// Pairing defines model for Pairing.
type Pairing struct {
	// Credential Returned once after pairing approval or token creation.
	Credential *IssuedCredential `json:"credential,omitempty"`
	ExpiresAt  time.Time         `json:"expiresAt"`
	Id         PairingId         `json:"id"`

	// Interval Minimum polling interval in seconds.
	Interval        int           `json:"interval"`
	Status          PairingStatus `json:"status"`
	UserCode        string        `json:"userCode"`
	VerificationUri string        `json:"verificationUri"`
}

// PairingStatus defines model for Pairing.Status.
type PairingStatus string

// PairingCreated defines model for PairingCreated.
type PairingCreated struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Id        PairingId `json:"id"`
	Interval  int       `json:"interval"`

	// PairingSecret One-time polling secret; never put it in a URL.
	PairingSecret   string               `json:"pairingSecret"`
	Status          PairingCreatedStatus `json:"status"`
	UserCode        string               `json:"userCode"`
	VerificationUri string               `json:"verificationUri"`
}

// PairingCreatedStatus defines model for PairingCreated.Status.
type PairingCreatedStatus string

// PairingId defines model for PairingId.
type PairingId = string

// RestrictedIdentifier defines model for RestrictedIdentifier.
type RestrictedIdentifier = string

// SenderCredential defines model for SenderCredential.
type SenderCredential struct {
	CreatedAt  time.Time            `json:"createdAt"`
	Id         string               `json:"id"`
	Kind       SenderCredentialKind `json:"kind"`
	LastUsedAt *time.Time           `json:"lastUsedAt,omitempty"`
	Name       string               `json:"name"`
}

// SenderCredentialKind defines model for SenderCredential.Kind.
type SenderCredentialKind string

// Usage defines model for Usage.
type Usage struct {
	Limit       int       `json:"limit"`
	PeriodEnd   time.Time `json:"periodEnd"`
	PeriodStart time.Time `json:"periodStart"`
	Used        int       `json:"used"`
}

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// APIError defines model for APIError.
type APIError = ErrorResponse

// ListOwnMessagesParams defines parameters for ListOwnMessages.
type ListOwnMessagesParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreatePairingJSONBody defines parameters for CreatePairing.
type CreatePairingJSONBody struct {
	Platform      CreatePairingJSONBodyPlatform `json:"platform"`
	SuggestedName string                        `json:"suggestedName"`
}

// CreatePairingJSONBodyPlatform defines parameters for CreatePairing.
type CreatePairingJSONBodyPlatform string

// GetPairingParams defines parameters for GetPairing.
type GetPairingParams struct {
	// PairingSecret One-time secret returned out of band when pairing is created.
	PairingSecret string `json:"pairingSecret"`
}

// UpdateCurrentSenderCredentialJSONBody defines parameters for UpdateCurrentSenderCredential.
type UpdateCurrentSenderCredentialJSONBody struct {
	Name string `json:"name"`
}

// CreateMessageJSONRequestBody defines body for CreateMessage for application/json ContentType.
type CreateMessageJSONRequestBody = MessageInput

// CreatePairingJSONRequestBody defines body for CreatePairing for application/json ContentType.
type CreatePairingJSONRequestBody CreatePairingJSONBody

// UpdateCurrentSenderCredentialJSONRequestBody defines body for UpdateCurrentSenderCredential for application/json ContentType.
type UpdateCurrentSenderCredentialJSONRequestBody UpdateCurrentSenderCredentialJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListDevices List receiving devices visible to the sender.
	//
	// Corresponds with GET /devices (the `ListDevices` operationId).
	ListDevices(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListOwnMessages List messages sent by the authenticated paired CLI.
	//
	// Corresponds with GET /messages (the `ListOwnMessages` operationId).
	ListOwnMessages(ctx context.Context, params *ListOwnMessagesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateMessageWithBody Accept a push message for delivery.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /messages (the `CreateMessage` operationId).
	CreateMessageWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateMessage Accept a push message for delivery.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /messages (the `CreateMessage` operationId).
	CreateMessage(ctx context.Context, body CreateMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePairingWithBody Start pairing a CLI.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /pairings (the `CreatePairing` operationId).
	CreatePairingWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePairing Start pairing a CLI.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /pairings (the `CreatePairing` operationId).
	CreatePairing(ctx context.Context, body CreatePairingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPairing Poll a pairing attempt.
	//
	// Corresponds with GET /pairings/{pairingId} (the `GetPairing` operationId).
	GetPairing(ctx context.Context, pairingId PairingId, params *GetPairingParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RevokeCurrentSenderCredential Revoke the authenticated paired CLI.
	//
	// Corresponds with DELETE /sender-credentials/current (the `RevokeCurrentSenderCredential` operationId).
	RevokeCurrentSenderCredential(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCurrentSenderCredential Show the authenticated paired CLI.
	//
	// Corresponds with GET /sender-credentials/current (the `GetCurrentSenderCredential` operationId).
	GetCurrentSenderCredential(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateCurrentSenderCredentialWithBody Rename the authenticated paired CLI.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PATCH /sender-credentials/current (the `UpdateCurrentSenderCredential` operationId).
	UpdateCurrentSenderCredentialWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateCurrentSenderCredential Rename the authenticated paired CLI.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PATCH /sender-credentials/current (the `UpdateCurrentSenderCredential` operationId).
	UpdateCurrentSenderCredential(ctx context.Context, body UpdateCurrentSenderCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsage Get current account send usage.
	//
	// Corresponds with GET /usage (the `GetUsage` operationId).
	GetUsage(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListDevices List receiving devices visible to the sender.
//
// Corresponds with GET /devices (the `ListDevices` operationId).
func (c *Client) ListDevices(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDevicesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListOwnMessages List messages sent by the authenticated paired CLI.
//
// Corresponds with GET /messages (the `ListOwnMessages` operationId).
func (c *Client) ListOwnMessages(ctx context.Context, params *ListOwnMessagesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListOwnMessagesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateMessageWithBody Accept a push message for delivery.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /messages (the `CreateMessage` operationId).
func (c *Client) CreateMessageWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateMessageRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateMessage Accept a push message for delivery.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /messages (the `CreateMessage` operationId).
func (c *Client) CreateMessage(ctx context.Context, body CreateMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateMessageRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreatePairingWithBody Start pairing a CLI.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /pairings (the `CreatePairing` operationId).
func (c *Client) CreatePairingWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePairingRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreatePairing Start pairing a CLI.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /pairings (the `CreatePairing` operationId).
func (c *Client) CreatePairing(ctx context.Context, body CreatePairingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePairingRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetPairing Poll a pairing attempt.
//
// Corresponds with GET /pairings/{pairingId} (the `GetPairing` operationId).
func (c *Client) GetPairing(ctx context.Context, pairingId PairingId, params *GetPairingParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPairingRequest(c.Server, pairingId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RevokeCurrentSenderCredential Revoke the authenticated paired CLI.
//
// Corresponds with DELETE /sender-credentials/current (the `RevokeCurrentSenderCredential` operationId).
func (c *Client) RevokeCurrentSenderCredential(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeCurrentSenderCredentialRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetCurrentSenderCredential Show the authenticated paired CLI.
//
// Corresponds with GET /sender-credentials/current (the `GetCurrentSenderCredential` operationId).
func (c *Client) GetCurrentSenderCredential(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCurrentSenderCredentialRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateCurrentSenderCredentialWithBody Rename the authenticated paired CLI.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PATCH /sender-credentials/current (the `UpdateCurrentSenderCredential` operationId).
func (c *Client) UpdateCurrentSenderCredentialWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateCurrentSenderCredentialRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateCurrentSenderCredential Rename the authenticated paired CLI.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PATCH /sender-credentials/current (the `UpdateCurrentSenderCredential` operationId).
func (c *Client) UpdateCurrentSenderCredential(ctx context.Context, body UpdateCurrentSenderCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateCurrentSenderCredentialRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetUsage Get current account send usage.
//
// Corresponds with GET /usage (the `GetUsage` operationId).
func (c *Client) GetUsage(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsageRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListDevicesRequest constructs an http.Request for the ListDevices method
func NewListDevicesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/devices")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListOwnMessagesRequest constructs an http.Request for the ListOwnMessages method
func NewListOwnMessagesRequest(server string, params *ListOwnMessagesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/messages")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateMessageRequest calls the generic CreateMessage builder with application/json body
func NewCreateMessageRequest(server string, body CreateMessageJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateMessageRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateMessageRequestWithBody constructs an http.Request for the CreateMessage method, with any body, and a specified content type
func NewCreateMessageRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/messages")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreatePairingRequest calls the generic CreatePairing builder with application/json body
func NewCreatePairingRequest(server string, body CreatePairingJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePairingRequestWithBody(server, "application/json", bodyReader)
}

// NewCreatePairingRequestWithBody constructs an http.Request for the CreatePairing method, with any body, and a specified content type
func NewCreatePairingRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pairings")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetPairingRequest constructs an http.Request for the GetPairing method
func NewGetPairingRequest(server string, pairingId PairingId, params *GetPairingParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "pairingId", pairingId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pairings/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "pairingSecret", params.PairingSecret, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("pairingSecret", headerParam0)

	}

	return req, nil
}

// NewRevokeCurrentSenderCredentialRequest constructs an http.Request for the RevokeCurrentSenderCredential method
func NewRevokeCurrentSenderCredentialRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sender-credentials/current")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCurrentSenderCredentialRequest constructs an http.Request for the GetCurrentSenderCredential method
func NewGetCurrentSenderCredentialRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sender-credentials/current")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateCurrentSenderCredentialRequest calls the generic UpdateCurrentSenderCredential builder with application/json body
func NewUpdateCurrentSenderCredentialRequest(server string, body UpdateCurrentSenderCredentialJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateCurrentSenderCredentialRequestWithBody(server, "application/json", bodyReader)
}

// NewUpdateCurrentSenderCredentialRequestWithBody constructs an http.Request for the UpdateCurrentSenderCredential method, with any body, and a specified content type
func NewUpdateCurrentSenderCredentialRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sender-credentials/current")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetUsageRequest constructs an http.Request for the GetUsage method
func NewGetUsageRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/usage")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListDevicesWithResponse List receiving devices visible to the sender.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /devices (the `ListDevices` operationId).
	ListDevicesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDevicesResponse, error)

	// ListOwnMessagesWithResponse List messages sent by the authenticated paired CLI.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /messages (the `ListOwnMessages` operationId).
	ListOwnMessagesWithResponse(ctx context.Context, params *ListOwnMessagesParams, reqEditors ...RequestEditorFn) (*ListOwnMessagesResponse, error)

	// CreateMessageWithBodyWithResponse Accept a push message for delivery.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /messages (the `CreateMessage` operationId).
	CreateMessageWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateMessageResponse, error)

	// CreateMessageWithResponse Accept a push message for delivery.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /messages (the `CreateMessage` operationId).
	CreateMessageWithResponse(ctx context.Context, body CreateMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateMessageResponse, error)

	// CreatePairingWithBodyWithResponse Start pairing a CLI.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /pairings (the `CreatePairing` operationId).
	CreatePairingWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePairingResponse, error)

	// CreatePairingWithResponse Start pairing a CLI.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /pairings (the `CreatePairing` operationId).
	CreatePairingWithResponse(ctx context.Context, body CreatePairingJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePairingResponse, error)

	// GetPairingWithResponse Poll a pairing attempt.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /pairings/{pairingId} (the `GetPairing` operationId).
	GetPairingWithResponse(ctx context.Context, pairingId PairingId, params *GetPairingParams, reqEditors ...RequestEditorFn) (*GetPairingResponse, error)

	// RevokeCurrentSenderCredentialWithResponse Revoke the authenticated paired CLI.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /sender-credentials/current (the `RevokeCurrentSenderCredential` operationId).
	RevokeCurrentSenderCredentialWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*RevokeCurrentSenderCredentialResponse, error)

	// GetCurrentSenderCredentialWithResponse Show the authenticated paired CLI.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /sender-credentials/current (the `GetCurrentSenderCredential` operationId).
	GetCurrentSenderCredentialWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCurrentSenderCredentialResponse, error)

	// UpdateCurrentSenderCredentialWithBodyWithResponse Rename the authenticated paired CLI.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /sender-credentials/current (the `UpdateCurrentSenderCredential` operationId).
	UpdateCurrentSenderCredentialWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateCurrentSenderCredentialResponse, error)

	// UpdateCurrentSenderCredentialWithResponse Rename the authenticated paired CLI.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /sender-credentials/current (the `UpdateCurrentSenderCredential` operationId).
	UpdateCurrentSenderCredentialWithResponse(ctx context.Context, body UpdateCurrentSenderCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateCurrentSenderCredentialResponse, error)

	// GetUsageWithResponse Get current account send usage.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /usage (the `GetUsage` operationId).
	GetUsageWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUsageResponse, error)
}

// ListDevicesResponseDefaultHeaders the declared response headers of an HTTP default response for ListDevices
type ListDevicesResponseDefaultHeaders struct {
	RetryAfter *int
	XRequestID *string
}

type ListDevicesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Items []Device `json:"items"`
	}
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *APIError
	// HeadersDefault the parsed response headers for an HTTP default response
	HeadersDefault *ListDevicesResponseDefaultHeaders
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListDevicesResponse) GetJSON200() *struct {
	Items []Device `json:"items"`
} {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r ListDevicesResponse) GetJSONDefault() *APIError {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r ListDevicesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListDevicesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDevicesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDevicesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListOwnMessagesResponseDefaultHeaders the declared response headers of an HTTP default response for ListOwnMessages
type ListOwnMessagesResponseDefaultHeaders struct {
	RetryAfter *int
	XRequestID *string
}

type ListOwnMessagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *MessagePage
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *APIError
	// HeadersDefault the parsed response headers for an HTTP default response
	HeadersDefault *ListOwnMessagesResponseDefaultHeaders
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListOwnMessagesResponse) GetJSON200() *MessagePage {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r ListOwnMessagesResponse) GetJSONDefault() *APIError {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r ListOwnMessagesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListOwnMessagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListOwnMessagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListOwnMessagesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CreateMessageResponseDefaultHeaders the declared response headers of an HTTP default response for CreateMessage
type CreateMessageResponseDefaultHeaders struct {
	RetryAfter *int
	XRequestID *string
}

type CreateMessageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *MessageAccepted
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *APIError
	// HeadersDefault the parsed response headers for an HTTP default response
	HeadersDefault *CreateMessageResponseDefaultHeaders
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r CreateMessageResponse) GetJSON202() *MessageAccepted {
	return r.JSON202
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r CreateMessageResponse) GetJSONDefault() *APIError {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r CreateMessageResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateMessageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateMessageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateMessageResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CreatePairingResponseDefaultHeaders the declared response headers of an HTTP default response for CreatePairing
type CreatePairingResponseDefaultHeaders struct {
	RetryAfter *int
	XRequestID *string
}

type CreatePairingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *PairingCreated
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *APIError
	// HeadersDefault the parsed response headers for an HTTP default response
	HeadersDefault *CreatePairingResponseDefaultHeaders
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreatePairingResponse) GetJSON201() *PairingCreated {
	return r.JSON201
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r CreatePairingResponse) GetJSONDefault() *APIError {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r CreatePairingResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreatePairingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePairingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreatePairingResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetPairingResponseDefaultHeaders the declared response headers of an HTTP default response for GetPairing
type GetPairingResponseDefaultHeaders struct {
	RetryAfter *int
	XRequestID *string
}

type GetPairingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Pairing
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *APIError
	// HeadersDefault the parsed response headers for an HTTP default response
	HeadersDefault *GetPairingResponseDefaultHeaders
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetPairingResponse) GetJSON200() *Pairing {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetPairingResponse) GetJSONDefault() *APIError {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetPairingResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetPairingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPairingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPairingResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// RevokeCurrentSenderCredentialResponseDefaultHeaders the declared response headers of an HTTP default response for RevokeCurrentSenderCredential
type RevokeCurrentSenderCredentialResponseDefaultHeaders struct {
	RetryAfter *int
	XRequestID *string
}

type RevokeCurrentSenderCredentialResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *APIError
	// HeadersDefault the parsed response headers for an HTTP default response
	HeadersDefault *RevokeCurrentSenderCredentialResponseDefaultHeaders
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r RevokeCurrentSenderCredentialResponse) GetJSONDefault() *APIError {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r RevokeCurrentSenderCredentialResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RevokeCurrentSenderCredentialResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeCurrentSenderCredentialResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RevokeCurrentSenderCredentialResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetCurrentSenderCredentialResponseDefaultHeaders the declared response headers of an HTTP default response for GetCurrentSenderCredential
type GetCurrentSenderCredentialResponseDefaultHeaders struct {
	RetryAfter *int
	XRequestID *string
}

type GetCurrentSenderCredentialResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *SenderCredential
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *APIError
	// HeadersDefault the parsed response headers for an HTTP default response
	HeadersDefault *GetCurrentSenderCredentialResponseDefaultHeaders
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetCurrentSenderCredentialResponse) GetJSON200() *SenderCredential {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetCurrentSenderCredentialResponse) GetJSONDefault() *APIError {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetCurrentSenderCredentialResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetCurrentSenderCredentialResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCurrentSenderCredentialResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCurrentSenderCredentialResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// UpdateCurrentSenderCredentialResponseDefaultHeaders the declared response headers of an HTTP default response for UpdateCurrentSenderCredential
type UpdateCurrentSenderCredentialResponseDefaultHeaders struct {
	RetryAfter *int
	XRequestID *string
}

type UpdateCurrentSenderCredentialResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *SenderCredential
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *APIError
	// HeadersDefault the parsed response headers for an HTTP default response
	HeadersDefault *UpdateCurrentSenderCredentialResponseDefaultHeaders
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpdateCurrentSenderCredentialResponse) GetJSON200() *SenderCredential {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r UpdateCurrentSenderCredentialResponse) GetJSONDefault() *APIError {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r UpdateCurrentSenderCredentialResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpdateCurrentSenderCredentialResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateCurrentSenderCredentialResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateCurrentSenderCredentialResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetUsageResponseDefaultHeaders the declared response headers of an HTTP default response for GetUsage
type GetUsageResponseDefaultHeaders struct {
	RetryAfter *int
	XRequestID *string
}

type GetUsageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Usage
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *APIError
	// HeadersDefault the parsed response headers for an HTTP default response
	HeadersDefault *GetUsageResponseDefaultHeaders
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetUsageResponse) GetJSON200() *Usage {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetUsageResponse) GetJSONDefault() *APIError {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetUsageResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetUsageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetUsageResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListDevicesWithResponse List receiving devices visible to the sender.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /devices (the `ListDevices` operationId).
func (c *ClientWithResponses) ListDevicesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDevicesResponse, error) {
	rsp, err := c.ListDevices(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDevicesResponse(rsp)
}

// ListOwnMessagesWithResponse List messages sent by the authenticated paired CLI.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /messages (the `ListOwnMessages` operationId).
func (c *ClientWithResponses) ListOwnMessagesWithResponse(ctx context.Context, params *ListOwnMessagesParams, reqEditors ...RequestEditorFn) (*ListOwnMessagesResponse, error) {
	rsp, err := c.ListOwnMessages(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListOwnMessagesResponse(rsp)
}

// CreateMessageWithBodyWithResponse Accept a push message for delivery.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /messages (the `CreateMessage` operationId).
func (c *ClientWithResponses) CreateMessageWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateMessageResponse, error) {
	rsp, err := c.CreateMessageWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateMessageResponse(rsp)
}

// CreateMessageWithResponse Accept a push message for delivery.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /messages (the `CreateMessage` operationId).
func (c *ClientWithResponses) CreateMessageWithResponse(ctx context.Context, body CreateMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateMessageResponse, error) {
	rsp, err := c.CreateMessage(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateMessageResponse(rsp)
}

// CreatePairingWithBodyWithResponse Start pairing a CLI.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /pairings (the `CreatePairing` operationId).
func (c *ClientWithResponses) CreatePairingWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePairingResponse, error) {
	rsp, err := c.CreatePairingWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePairingResponse(rsp)
}

// CreatePairingWithResponse Start pairing a CLI.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /pairings (the `CreatePairing` operationId).
func (c *ClientWithResponses) CreatePairingWithResponse(ctx context.Context, body CreatePairingJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePairingResponse, error) {
	rsp, err := c.CreatePairing(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePairingResponse(rsp)
}

// GetPairingWithResponse Poll a pairing attempt.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /pairings/{pairingId} (the `GetPairing` operationId).
func (c *ClientWithResponses) GetPairingWithResponse(ctx context.Context, pairingId PairingId, params *GetPairingParams, reqEditors ...RequestEditorFn) (*GetPairingResponse, error) {
	rsp, err := c.GetPairing(ctx, pairingId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPairingResponse(rsp)
}

// RevokeCurrentSenderCredentialWithResponse Revoke the authenticated paired CLI.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /sender-credentials/current (the `RevokeCurrentSenderCredential` operationId).
func (c *ClientWithResponses) RevokeCurrentSenderCredentialWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*RevokeCurrentSenderCredentialResponse, error) {
	rsp, err := c.RevokeCurrentSenderCredential(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeCurrentSenderCredentialResponse(rsp)
}

// GetCurrentSenderCredentialWithResponse Show the authenticated paired CLI.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /sender-credentials/current (the `GetCurrentSenderCredential` operationId).
func (c *ClientWithResponses) GetCurrentSenderCredentialWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCurrentSenderCredentialResponse, error) {
	rsp, err := c.GetCurrentSenderCredential(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCurrentSenderCredentialResponse(rsp)
}

// UpdateCurrentSenderCredentialWithBodyWithResponse Rename the authenticated paired CLI.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /sender-credentials/current (the `UpdateCurrentSenderCredential` operationId).
func (c *ClientWithResponses) UpdateCurrentSenderCredentialWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateCurrentSenderCredentialResponse, error) {
	rsp, err := c.UpdateCurrentSenderCredentialWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateCurrentSenderCredentialResponse(rsp)
}

// UpdateCurrentSenderCredentialWithResponse Rename the authenticated paired CLI.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /sender-credentials/current (the `UpdateCurrentSenderCredential` operationId).
func (c *ClientWithResponses) UpdateCurrentSenderCredentialWithResponse(ctx context.Context, body UpdateCurrentSenderCredentialJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateCurrentSenderCredentialResponse, error) {
	rsp, err := c.UpdateCurrentSenderCredential(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateCurrentSenderCredentialResponse(rsp)
}

// GetUsageWithResponse Get current account send usage.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /usage (the `GetUsage` operationId).
func (c *ClientWithResponses) GetUsageWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetUsageResponse, error) {
	rsp, err := c.GetUsage(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsageResponse(rsp)
}

// ParseListDevicesResponse parses an HTTP response from a ListDevicesWithResponse call
func ParseListDevicesResponse(rsp *http.Response) (*ListDevicesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDevicesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Items []Device `json:"items"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	switch {
	case true:
		var headers ListDevicesResponseDefaultHeaders
		if values := rsp.Header.Values("Retry-After"); len(values) > 0 {
			var value int
			if err := runtime.BindStyledParameterWithOptions("simple", "Retry-After", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""}); err != nil {
				return nil, err
			}
			headers.RetryAfter = &value
		}
		if values := rsp.Header.Values("X-Request-ID"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XRequestID = &value
		}
		response.HeadersDefault = &headers
	}

	return response, nil
}

// ParseListOwnMessagesResponse parses an HTTP response from a ListOwnMessagesWithResponse call
func ParseListOwnMessagesResponse(rsp *http.Response) (*ListOwnMessagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListOwnMessagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MessagePage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	switch {
	case true:
		var headers ListOwnMessagesResponseDefaultHeaders
		if values := rsp.Header.Values("Retry-After"); len(values) > 0 {
			var value int
			if err := runtime.BindStyledParameterWithOptions("simple", "Retry-After", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""}); err != nil {
				return nil, err
			}
			headers.RetryAfter = &value
		}
		if values := rsp.Header.Values("X-Request-ID"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XRequestID = &value
		}
		response.HeadersDefault = &headers
	}

	return response, nil
}

// ParseCreateMessageResponse parses an HTTP response from a CreateMessageWithResponse call
func ParseCreateMessageResponse(rsp *http.Response) (*CreateMessageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateMessageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest MessageAccepted
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	switch {
	case true:
		var headers CreateMessageResponseDefaultHeaders
		if values := rsp.Header.Values("Retry-After"); len(values) > 0 {
			var value int
			if err := runtime.BindStyledParameterWithOptions("simple", "Retry-After", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""}); err != nil {
				return nil, err
			}
			headers.RetryAfter = &value
		}
		if values := rsp.Header.Values("X-Request-ID"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XRequestID = &value
		}
		response.HeadersDefault = &headers
	}

	return response, nil
}

// ParseCreatePairingResponse parses an HTTP response from a CreatePairingWithResponse call
func ParseCreatePairingResponse(rsp *http.Response) (*CreatePairingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePairingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest PairingCreated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	switch {
	case true:
		var headers CreatePairingResponseDefaultHeaders
		if values := rsp.Header.Values("Retry-After"); len(values) > 0 {
			var value int
			if err := runtime.BindStyledParameterWithOptions("simple", "Retry-After", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""}); err != nil {
				return nil, err
			}
			headers.RetryAfter = &value
		}
		if values := rsp.Header.Values("X-Request-ID"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XRequestID = &value
		}
		response.HeadersDefault = &headers
	}

	return response, nil
}

// ParseGetPairingResponse parses an HTTP response from a GetPairingWithResponse call
func ParseGetPairingResponse(rsp *http.Response) (*GetPairingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPairingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Pairing
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	switch {
	case true:
		var headers GetPairingResponseDefaultHeaders
		if values := rsp.Header.Values("Retry-After"); len(values) > 0 {
			var value int
			if err := runtime.BindStyledParameterWithOptions("simple", "Retry-After", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""}); err != nil {
				return nil, err
			}
			headers.RetryAfter = &value
		}
		if values := rsp.Header.Values("X-Request-ID"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XRequestID = &value
		}
		response.HeadersDefault = &headers
	}

	return response, nil
}

// ParseRevokeCurrentSenderCredentialResponse parses an HTTP response from a RevokeCurrentSenderCredentialWithResponse call
func ParseRevokeCurrentSenderCredentialResponse(rsp *http.Response) (*RevokeCurrentSenderCredentialResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeCurrentSenderCredentialResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	switch {
	case true:
		var headers RevokeCurrentSenderCredentialResponseDefaultHeaders
		if values := rsp.Header.Values("Retry-After"); len(values) > 0 {
			var value int
			if err := runtime.BindStyledParameterWithOptions("simple", "Retry-After", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""}); err != nil {
				return nil, err
			}
			headers.RetryAfter = &value
		}
		if values := rsp.Header.Values("X-Request-ID"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XRequestID = &value
		}
		response.HeadersDefault = &headers
	}

	return response, nil
}

// ParseGetCurrentSenderCredentialResponse parses an HTTP response from a GetCurrentSenderCredentialWithResponse call
func ParseGetCurrentSenderCredentialResponse(rsp *http.Response) (*GetCurrentSenderCredentialResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCurrentSenderCredentialResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SenderCredential
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	switch {
	case true:
		var headers GetCurrentSenderCredentialResponseDefaultHeaders
		if values := rsp.Header.Values("Retry-After"); len(values) > 0 {
			var value int
			if err := runtime.BindStyledParameterWithOptions("simple", "Retry-After", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""}); err != nil {
				return nil, err
			}
			headers.RetryAfter = &value
		}
		if values := rsp.Header.Values("X-Request-ID"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XRequestID = &value
		}
		response.HeadersDefault = &headers
	}

	return response, nil
}

// ParseUpdateCurrentSenderCredentialResponse parses an HTTP response from a UpdateCurrentSenderCredentialWithResponse call
func ParseUpdateCurrentSenderCredentialResponse(rsp *http.Response) (*UpdateCurrentSenderCredentialResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateCurrentSenderCredentialResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SenderCredential
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	switch {
	case true:
		var headers UpdateCurrentSenderCredentialResponseDefaultHeaders
		if values := rsp.Header.Values("Retry-After"); len(values) > 0 {
			var value int
			if err := runtime.BindStyledParameterWithOptions("simple", "Retry-After", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""}); err != nil {
				return nil, err
			}
			headers.RetryAfter = &value
		}
		if values := rsp.Header.Values("X-Request-ID"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XRequestID = &value
		}
		response.HeadersDefault = &headers
	}

	return response, nil
}

// ParseGetUsageResponse parses an HTTP response from a GetUsageWithResponse call
func ParseGetUsageResponse(rsp *http.Response) (*GetUsageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Usage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest APIError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	switch {
	case true:
		var headers GetUsageResponseDefaultHeaders
		if values := rsp.Header.Values("Retry-After"); len(values) > 0 {
			var value int
			if err := runtime.BindStyledParameterWithOptions("simple", "Retry-After", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""}); err != nil {
				return nil, err
			}
			headers.RetryAfter = &value
		}
		if values := rsp.Header.Values("X-Request-ID"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XRequestID = &value
		}
		response.HeadersDefault = &headers
	}

	return response, nil
}
